# Default values for ranger-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


image:
  repository: avs-alatau/ranger-admin-k8s
  pullPolicy: Always
  tag: "2.4.0"


imagePullSecrets: []
nameOverride: "ranger-admin"
fullnameOverride: "ranger-admin"


serviceAccount:
  create: false
  annotations: {}
  name: ""


podAnnotations: {}


podSecurityContext: {}


securityContext: {}


service:
  type: ClusterIP
  port: 6080


ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ranger-admin.dev.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

ranger_admin_conf:
  LDAP_PASSWORD: "LDAP_PASSWORD"
  LDAP_USERNAME: "LDAP_USERNAME"
  SOLR_PASSWORD: "SOLR_PASSWORD"
  SOLR_USER: "SOLR_USER"
  keyadmin_password: "keyadmin_password"
  rangerAdmin_password: "rangerAdmin_password"
  rangerTagsync_password: "rangerTagsync_password"
  rangerUsersync_password: "rangerUsersync_password"
  ranger_db_root_password: "ranger_db_root_password"
  ranger_db_root_user: "ranger_db_root_user"
  ranger_local_pass: "ranger_local_pass"
  ranger_db_user: "ranger_db_user"
  ranger_db_name: "ranger_db_name"
  db_password: "db_password"
  ranger_db_host: "ranger_db_host"
  ranger_scheduler_enabled: "true"
  ranger_ldap_ad_domain: "ranger_ldap_ad_domain"
  ldap_domen: "dev.local"
  ldap_user: "user_test"
  ldap_port: 389
  ranger_ldap_ad_base_dn: "DC=dev,DC=local"
  ranger_ldap_ad_bind_dn: "CN=LDAP_USERNAME,ldap_user_dn"
  ranger_ldap_ad_referral: "follow"
  ranger_ldap_ad_user_searchfilter: "(sAMAccountName={0})"
  ranger_supportedcomponents: "hdfs,yarn,hive,knox,ozone,tag,kafka"
  ranger_admin_cookie_name: "RANGERADMINSESSIONID"


resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 2
    memory: 4Gi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


nodeSelector: {}


tolerations: []


affinity: {}


script:

